<template>
  <div class="container">
    <div class="row" id="align-mid">
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <span>
          <transition name="shadow" enter-to-class="text-shadow-pop-bl">
            <h1 class="text-shadow-pop-over" v-if="show">
              <b>Start Your Journey</b>
            </h1>
          </transition>
        </span>
        <br />
        <span>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat.
          </p>
        </span>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 right-side">
        <Product />
      </div>
    </div>
  </div>
</template>

<script>
import Vue from "vue";
import Product from "@/components/cards/Product.vue";

export default Vue.extend({
  name: "Content",
  components: {
    Product
  },
  data: () => ({
    show: false
  }),
  created: function() {
    setTimeout(() => {
      this.show = true;
    }, 500);
  }
});
</script>

<style>
* {
  color: white;
}

.right-side {
  height: 500px;
}

.text-shadow-pop-bl {
  -webkit-animation: text-shadow-pop-bl 1s both;
  animation: text-shadow-pop-bl 1s both;
}

.text-shadow-pop-over {
  text-shadow: -1px 1px #555555, -2px 2px #555555, -3px 3px #555555,
    -4px 4px #555555, -5px 5px #555555, -6px 6px #555555, -7px 7px #555555,
    -8px 8px #555555;
  -webkit-transform: translateX(8px) translateY(-8px);
  transform: translateX(8px) translateY(-8px);
}
/* ----------------------------------------------
 * Generated by Animista on 2020-6-6 15:17:35
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-shadow-pop-bl
 * ----------------------------------------
 */
@-webkit-keyframes text-shadow-pop-bl {
  0% {
    text-shadow: 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555,
      0 0 #555555, 0 0 #555555, 0 0 #555555;
    -webkit-transform: translateX(0) translateY(0);
    transform: translateX(0) translateY(0);
  }
  100% {
    text-shadow: -1px 1px #555555, -2px 2px #555555, -3px 3px #555555,
      -4px 4px #555555, -5px 5px #555555, -6px 6px #555555, -7px 7px #555555,
      -8px 8px #555555;
    -webkit-transform: translateX(8px) translateY(-8px);
    transform: translateX(8px) translateY(-8px);
  }
}
@keyframes text-shadow-pop-bl {
  0% {
    text-shadow: 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555,
      0 0 #555555, 0 0 #555555, 0 0 #555555;
    -webkit-transform: translateX(0) translateY(0);
    transform: translateX(0) translateY(0);
  }
  100% {
    text-shadow: -1px 1px #555555, -2px 2px #555555, -3px 3px #555555,
      -4px 4px #555555, -5px 5px #555555, -6px 6px #555555, -7px 7px #555555,
      -8px 8px #555555;
    -webkit-transform: translateX(8px) translateY(-8px);
    transform: translateX(8px) translateY(-8px);
  }
}
</style>
